### ISSUE TITLE
Lofi Radio Link

### ISSUE THREAD

**Issue by joeyboli** [Grizz1e/HimalV2#10]
hello i am joey, i noticed you were using https://boxradio-edge-00.streamafrica.net/lofi
that is a link to my lofi radio, can i please know the incoming user-agent string to whitelist ?. we are constantly blocking FFMPEG user agents.

**Comment by Grizz1e** [comment]
Hi joey, the official Himal bot is no longer hosted and therefore has been offline for a few months (and there are no plans of making it online anytime soon). Many people who were self-hosting reported that your lofi radio was no longer working with the bot and are probably using alternative URLs. If you want me to remove your radio from the code, please let me know
