### ISSUE TITLE
Help Command Cannot Using any command

### ISSUE THREAD

**Issue by yourantithesis** [Grizz1e/HimalV2#7]
Slash command didn't showed up :(
![Screenshot_150](https://user-images.githubusercontent.com/111164892/197865079-96d3d72d-843c-4172-ac24-f58e94c42aef.png)

**Comment by Grizz1e** [comment]
Try registering the commands and then invite the bot to your server

**Comment by thenishantsapkota** [comment]
Use `docker-compose` instead for easier deployment

**Comment by yourantithesis** [comment]
> Try registering the commands and then invite the bot to your server

already done it, but when i try to run the bot on servers, the slash command didn't showed up :(

**Comment by yourantithesis** [comment]
> docker-compose

i'am using repl / glitch, so i can't use a docker :(

**Comment by Grizz1e** [comment]
if you've properly configured the `.env` file, it should register the command. If you're registering the commands globally, it will take some time before it shows up in your server. You might even need to reinvite the bot to you server **with the permission to create application commands**
